# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

# events that trigger CI workflow to run, so in this case, this will run when there's a push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# what the CI workflow can access, so here it only have read access
permissions:
  contents: read

# job is the task that will be ran
jobs:
  build:

    runs-on: ubuntu-latest

    # steps are instructions that the workflow executes
    steps:
    - uses: actions/checkout@v4       # downloads your code
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"        # gets python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi      # install requirements
    - name: Lint with flake8      # checks the style of the code and syntax errors etc. without running the code
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest      # runs the automated tests
      run: |
        pytest
